version: '3'
services:
  nginx1:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app1:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - php1
  php1:
    build:
      context: ./path/to/php1
    volumes:
      - ./app1:/var/www/html
    depends_on:
      - mysql
  nginx2:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app2:/var/www/html
    ports:
      - "8082:80"
    depends_on:
      - php2
  php2:
    build:
      context: ./path/to/php2
    volumes:
      - ./app2:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
